version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=development
      - LOG_LEVEL=debug
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
